import { describe, it, expect } from 'vitest'
import {
  incubationProgress,
  DEFAULT_INCUBATION_DAYS,
  INCUBATION_MILESTONES,
  calcRawWeightPerTray,
  calcSampleSummary,
  parseDate,
  daysFromNow,
  formatDays,
  getUpcomingEvents,
  getAllEvents,
  getIncubationDay,
  getTempRange,
  incubatorDisplay,
  checkTempHumidity,
  cToF,
  fToC,
  formatTemp,
  type Batch,
  trayYear,
  lbsToKg,
  perLbToPerKg,
  trayWeightKg,
  incubationStartFor,
  milestoneEvents,
  milestonesToIcs,
  dailyMeanTempByIncubator,
  holdingDays,
  runWindow,
  stageStartDay,
  expectedStageForDay,
  stageDelta,
} from './incubation'

describe('incubationProgress', () => {
  it('reports idle when there is no start date', () => {
    const p = incubationProgress(null, '2026-07-22T00:00:00Z')
    expect(p.stage).toBe('idle')
    expect(p.pct).toBe(0)
    expect(p.daysRemaining).toBe(DEFAULT_INCUBATION_DAYS)
  })

  it('is 0% on the start instant', () => {
    const p = incubationProgress('2026-07-01T00:00:00Z', '2026-07-01T00:00:00Z')
    expect(p.pct).toBe(0)
    expect(p.stage).toBe('early')
  })

  it('tracks the milestone schedule, not an arbitrary 21 days', () => {
    // DEFAULT_INCUBATION_DAYS must stay pinned to Expected Release, or the card
    // claims a run is finished while the calendar still has milestones ahead.
    const expectedRelease = INCUBATION_MILESTONES.find((m) => m.label === 'Expected Release')
    expect(DEFAULT_INCUBATION_DAYS).toBe(expectedRelease!.day)
  })

  it('is ~50% halfway through the cycle', () => {
    const half = DEFAULT_INCUBATION_DAYS / 2
    const start = Date.parse('2026-07-01T00:00:00Z')
    const p = incubationProgress('2026-07-01T00:00:00Z', new Date(start + half * 86400000).toISOString())
    expect(p.pct).toBe(50)
    expect(p.stage).toBe('mid')
    expect(p.overdue).toBe(false)
  })

  it('reports how far past schedule an overrun run is, rather than "0d left"', () => {
    // Day 64 of a 23-day schedule: the real case seen on the incubator cards.
    const p = incubationProgress('2026-06-01T00:00:00Z', '2026-08-04T00:00:00Z')
    expect(p.overdue).toBe(true)
    expect(p.daysOverdue).toBe(64 - DEFAULT_INCUBATION_DAYS)
    expect(p.daysRemaining).toBe(0)
  })

  it('flags emergence in the last stretch', () => {
    // Relative to the schedule, so this doesn't silently break if it changes.
    const start = Date.parse('2026-07-01T00:00:00Z')
    const day = DEFAULT_INCUBATION_DAYS * 0.9
    const p = incubationProgress('2026-07-01T00:00:00Z', new Date(start + day * 86400000).toISOString())
    expect(p.stage).toBe('emergence')
  })

  it('caps at 100% / complete when overdue', () => {
    const p = incubationProgress('2026-07-01T00:00:00Z', '2026-08-01T00:00:00Z')
    expect(p.pct).toBe(100)
    expect(p.daysRemaining).toBe(0)
    expect(p.stage).toBe('complete')
  })
})

// ── Ports of incubation_calc.py — values locked against the OLD Python ─────────
// Expected numbers below were generated by running bee-incubation/incubation_calc.py.

describe('calcRawWeightPerTray (calc_raw_weight_per_tray)', () => {
  it('matches Python across live %, target gallons, lbs/gal', () => {
    expect(calcRawWeightPerTray(0.82)).toBe(5.366)
    expect(calcRawWeightPerTray(0.9, 2.0, 2.2)).toBe(4.889)
    expect(calcRawWeightPerTray(0.5, 3.0, 2.5)).toBe(15.0)
    expect(calcRawWeightPerTray(1.0)).toBe(4.4)
    expect(calcRawWeightPerTray(0.333, 2.0, 2.2)).toBe(13.213)
  })
  it('returns 0 for non-positive live %', () => {
    expect(calcRawWeightPerTray(0.0)).toBe(0.0)
    expect(calcRawWeightPerTray(-0.2)).toBe(0.0)
  })
})

describe('calcSampleSummary (calc_sample_summary)', () => {
  it('matches Python (with banker-rounded half at 24.975 → 24.98)', () => {
    expect(calcSampleSummary(100.0, 0.82)).toEqual({
      liveGalsTotal: 82.0,
      trayCountExact: 41.0,
      trayCount: 41,
      rawGalsPerTray: 2.439,
      rawLbsPerTray: 5.366,
    })
    expect(calcSampleSummary(55.5, 0.9, 2.0, 2.2)).toEqual({
      liveGalsTotal: 49.95,
      trayCountExact: 24.98,
      trayCount: 24,
      rawGalsPerTray: 2.222,
      rawLbsPerTray: 4.889,
    })
    expect(calcSampleSummary(12.3, 0.777, 2.5, 2.1)).toEqual({
      liveGalsTotal: 9.56,
      trayCountExact: 3.82,
      trayCount: 3,
      rawGalsPerTray: 3.218,
      rawLbsPerTray: 6.757,
    })
  })
  it('zeroes out on missing volume or live %', () => {
    const zero = {
      liveGalsTotal: 0.0,
      trayCountExact: 0.0,
      trayCount: 0,
      rawGalsPerTray: 0.0,
      rawLbsPerTray: 0.0,
    }
    expect(calcSampleSummary(0, 0.8)).toEqual(zero)
    expect(calcSampleSummary(100, 0)).toEqual(zero)
  })
})

describe('parseDate (parse_date)', () => {
  it('parses ISO, US, and D/M/Y — trying %m/%d before %d/%m', () => {
    expect(parseDate('2026-07-22')).toEqual({ year: 2026, month: 7, day: 22 })
    expect(parseDate('2026-07-22T13:45:00Z')).toEqual({ year: 2026, month: 7, day: 22 })
    expect(parseDate('07/22/2026')).toEqual({ year: 2026, month: 7, day: 22 })
    expect(parseDate('22/07/2026')).toEqual({ year: 2026, month: 7, day: 22 }) // falls to %d/%m
  })
  it('rejects junk and impossible dates', () => {
    expect(parseDate(null)).toBeNull()
    expect(parseDate('')).toBeNull()
    expect(parseDate('bogus')).toBeNull()
    expect(parseDate('2026-13-01')).toBeNull()
    expect(parseDate('2026-02-30')).toBeNull()
  })
})

describe('date/day helpers', () => {
  const now = new Date('2026-07-22T09:00:00Z')
  it('daysFromNow is signed whole calendar days', () => {
    expect(daysFromNow('2026-07-22', now)).toBe(0)
    expect(daysFromNow('2026-07-25', now)).toBe(3)
    expect(daysFromNow('2026-07-21', now)).toBe(-1)
    expect(daysFromNow('nope', now)).toBeNull()
  })
  it('formatDays matches Python phrasing', () => {
    expect(formatDays(null)).toBe('—')
    expect(formatDays(0)).toBe('Today')
    expect(formatDays(1)).toBe('Tomorrow')
    expect(formatDays(-1)).toBe('Yesterday')
    expect(formatDays(3)).toBe('in 3d')
    expect(formatDays(-5)).toBe('5d ago')
    expect(formatDays(30)).toBe('in 30d')
  })
  it('getIncubationDay is 1-based from the start date', () => {
    expect(getIncubationDay({ startDate: '2026-07-20' }, now)).toBe(3)
    expect(getIncubationDay({ startDate: '2026-07-22' }, now)).toBe(1)
    expect(getIncubationDay({}, now)).toBeNull()
  })
})

describe('getUpcomingEvents / getAllEvents (get_upcoming_events)', () => {
  const now = new Date('2026-07-22T09:00:00Z')
  const batch: Batch = {
    id: 'b1',
    name: 'Batch One',
    incubatorName: 'Inc A',
    startDate: '2026-07-20',
    vaponaIn: '2026-07-22', // 0  → urgent
    vaponaOut: '2026-07-20', // -2 → dropped (before -1)
    airOut: '2026-07-25', // 3
    earliestCool: '2026-08-21', // 30 → boundary, kept
    estimatedRelease: '2026-08-30', // 39 → dropped (> 30)
    latestRelease: '2026-07-21', // -1 → urgent, kept
  }

  it('keeps events in [-1, lookahead], sorted by days away', () => {
    const events = getUpcomingEvents(batch, now)
    expect(events.map((e) => e.label)).toEqual([
      'Latest Release',
      'Vapona In',
      'Air Out',
      'Earliest Cool',
    ])
    expect(events.map((e) => e.daysAway)).toEqual([-1, 0, 3, 30])
    expect(events.map((e) => e.urgent)).toEqual([true, true, false, false])
    expect(events[0]).toMatchObject({ batchName: 'Batch One', batchId: 'b1', incubatorName: 'Inc A' })
  })

  it('respects a shorter lookahead window', () => {
    const events = getUpcomingEvents(batch, now, 5)
    expect(events.map((e) => e.label)).toEqual(['Latest Release', 'Vapona In', 'Air Out'])
  })

  it('merges + sorts across batches', () => {
    const b2: Batch = { id: 'b2', name: 'Batch Two', airOut: '2026-07-23' } // 1
    const all = getAllEvents([batch, b2], now)
    expect(all.map((e) => e.daysAway)).toEqual([-1, 0, 1, 3, 30])
  })
})

describe('temperature modes + threshold checks', () => {
  it('getTempRange maps modes, defaults unknown/blank to incubation', () => {
    expect(getTempRange({ tempMode: 'incubation' })).toEqual([25.0, 35.0])
    expect(getTempRange({ tempMode: 'cool_storage' })).toEqual([0.0, 12.0])
    expect(getTempRange({ tempMode: 'holding' })).toEqual([10.0, 18.0])
    expect(getTempRange({ tempMode: 'off' })).toEqual([null, null])
    expect(getTempRange({})).toEqual([25.0, 35.0])
    expect(getTempRange({ tempMode: 'bogus' })).toEqual([25.0, 35.0])
  })
  it('checkTempHumidity flags out-of-range temps (Off = no alerts)', () => {
    expect(checkTempHumidity({ name: 'A', tempMode: 'incubation' }, 20.0, 50)).toEqual([
      'A: Temp 20.0°C below minimum 25.0°C',
    ])
    expect(checkTempHumidity({ name: 'A', tempMode: 'incubation' }, 40.04, 50)).toEqual([
      'A: Temp 40.0°C above maximum 35.0°C',
    ])
    expect(checkTempHumidity({ name: 'A', tempMode: 'incubation' }, 30.0, 50)).toEqual([])
    expect(checkTempHumidity({ id: 7, tempMode: 'off' }, 99.0, 50)).toEqual([])
    expect(checkTempHumidity({ id: 7, tempMode: 'holding' }, 9.95, 50)).toEqual([
      'Incubator 7: Temp 9.9°C below minimum 10.0°C',
    ])
  })
})

describe('incubatorDisplay', () => {
  it('derives mode label + temp band from the live temp_mode', () => {
    expect(incubatorDisplay({ tempMode: 'incubation', humidityMin: 55, humidityMax: 75 })).toEqual({
      modeLabel: 'Incubation',
      running: true,
      tempMin: 25,
      tempMax: 35,
      humMin: 55,
      humMax: 75,
    })
    expect(incubatorDisplay({ tempMode: 'off' })).toMatchObject({ modeLabel: 'Off', running: false, tempMin: null })
    expect(incubatorDisplay({ tempMode: 'cool_storage' })).toMatchObject({
      modeLabel: 'Cool Storage',
      running: true,
      tempMin: 0,
      tempMax: 12,
    })
  })
  it('falls back to app status when there is no live mode (mock mode)', () => {
    expect(incubatorDisplay({ status: 'active' })).toMatchObject({ modeLabel: 'Active', running: true, tempMin: null })
    expect(incubatorDisplay({ status: 'idle' })).toMatchObject({ modeLabel: 'Idle', running: false })
  })
})

describe('unit conversion', () => {
  it('cToF matches Python (rounded to 0.1)', () => {
    expect(cToF(0)).toBe(32.0)
    expect(cToF(30)).toBe(86.0)
    expect(cToF(25.5)).toBe(77.9)
    expect(cToF(-1.25)).toBe(29.8)
    expect(cToF(37.777)).toBe(100.0)
  })
  it('fToC matches Python (rounded to 0.1)', () => {
    expect(fToC(32)).toBe(0.0)
    expect(fToC(98.6)).toBe(37.0)
    expect(fToC(0)).toBe(-17.8)
    expect(fToC(-40)).toBe(-40.0)
    expect(fToC(100.05)).toBe(37.8)
  })
  it('formatTemp renders one decimal with the right unit', () => {
    expect(formatTemp(25.0, 'C')).toBe('25.0°C')
    expect(formatTemp(25.0, 'F')).toBe('77.0°F')
    expect(formatTemp(-1.24, 'C')).toBe('-1.2°C')
    expect(formatTemp(30.06, 'F')).toBe('86.1°F')
  })
})

describe('trayYear + unit helpers', () => {
  it('prefers out, then cool, then in date', () => {
    expect(trayYear({ outDate: '2026-07-28', coolDate: '2025-01-01', inDate: '2024-01-01' })).toBe(2026)
    expect(trayYear({ outDate: null, coolDate: '2025-06-02', inDate: '2024-01-01' })).toBe(2025)
    expect(trayYear({ outDate: null, coolDate: null, inDate: '2024-05-05' })).toBe(2024)
  })

  it('returns null when a tray has no dates ("undated" is a real bucket)', () => {
    expect(trayYear({})).toBeNull()
    expect(trayYear({ outDate: null, coolDate: null, inDate: null })).toBeNull()
  })

  it('converts pounds and per-pound rates to metric, passing null through', () => {
    expect(lbsToKg(100)).toBeCloseTo(45.359237, 6)
    expect(lbsToKg(null)).toBeNull()
    // 4475 bees/lb is ~9866 bees/kg
    expect(perLbToPerKg(4475)).toBeCloseTo(9866.0, 0)
    expect(perLbToPerKg(null)).toBeNull()
  })
})

describe('trayWeightKg', () => {
  it('prefers the stored kg figure', () => {
    expect(trayWeightKg({ kgPer2Gal: 2.57, lbsPer2Gal: 5.66 })).toBe(2.57)
  })

  it('falls back to converting the pounds figure', () => {
    expect(trayWeightKg({ kgPer2Gal: null, lbsPer2Gal: 5.66 })).toBeCloseTo(2.567, 3)
  })

  it('is null when the sample has no per-tray weight, or no sample at all', () => {
    expect(trayWeightKg({ kgPer2Gal: null, lbsPer2Gal: null })).toBeNull()
    expect(trayWeightKg(null)).toBeNull()
    expect(trayWeightKg(undefined)).toBeNull()
  })
})

describe('incubation milestones', () => {
  const trays = [
    { incubatorId: 'i1', status: 'active', inDate: '2026-06-01' },
    { incubatorId: 'i1', status: 'active', inDate: '2026-06-01' },
    { incubatorId: 'i1', status: 'active', inDate: '2026-06-03' },
    { incubatorId: 'i1', status: 'released', inDate: '2025-01-01' }, // ignored
    { incubatorId: 'i2', status: 'active', inDate: null },
  ]

  it('prefers the explicit start date', () => {
    expect(incubationStartFor({ id: 'i1', incubationStart: '2026-07-10' }, trays)).toBe('2026-07-10')
  })

  it('treats "none" as schedule removed, not as a date to derive', () => {
    expect(incubationStartFor({ id: 'i1', incubationStart: 'none' }, trays)).toBeNull()
  })

  it('falls back to the most common in-date among ACTIVE trays', () => {
    expect(incubationStartFor({ id: 'i1', incubationStart: null }, trays)).toBe('2026-06-01')
  })

  it('is null when nothing gives a start date', () => {
    expect(incubationStartFor({ id: 'i2', incubationStart: '' }, trays)).toBeNull()
  })

  it('places day N at start + (N-1), so day 1 is the start', () => {
    const evs = milestoneEvents([{ id: 'i1', name: 'Inc 1', incubationStart: '2026-06-01' }], [])
    expect(evs[0]).toMatchObject({ day: 1, label: 'Incubation Start', date: '2026-06-01' })
    expect(evs.find((e) => e.day === 7)?.date).toBe('2026-06-07')
    expect(evs.find((e) => e.day === 23)?.date).toBe('2026-06-23')
    expect(evs.find((e) => e.day === 37)?.date).toBe('2026-07-07') // crosses the month
  })

  it('skips incubators with no start date', () => {
    const evs = milestoneEvents(
      [
        { id: 'i1', name: 'Inc 1', incubationStart: '2026-06-01' },
        { id: 'i2', name: 'Inc 2', incubationStart: null },
      ],
      [],
    )
    expect(new Set(evs.map((e) => e.incubatorId))).toEqual(new Set(['i1']))
  })

  it('skips an incubator that is switched off', () => {
    const evs = milestoneEvents(
      [
        { id: 'i1', name: 'Inc 1', incubationStart: '2026-06-01', tempMode: 'incubation' },
        { id: 'i2', name: 'Inc 2', incubationStart: '2026-06-01', tempMode: 'off' },
      ],
      [],
    )
    expect(new Set(evs.map((e) => e.incubatorId))).toEqual(new Set(['i1']))
  })

  it('does not invent a run from a stray tray left in an off incubator', () => {
    // The live case: Incubator 1 off, no start date, one active tray still
    // assigned to it. The tray fallback would otherwise plot Day 1 → Day 37.
    const trays = [{ incubatorId: 'i1', status: 'active', inDate: '2026-08-04' }]
    expect(milestoneEvents([{ id: 'i1', name: 'Inc 1', incubationStart: null, tempMode: 'off' }], trays)).toEqual([])
    // Same data, incubator actually running → the fallback is still wanted.
    expect(
      milestoneEvents([{ id: 'i1', name: 'Inc 1', incubationStart: null, tempMode: 'incubation' }], trays).length,
    ).toBe(INCUBATION_MILESTONES.length)
  })

  it('keeps plotting through holding and cool storage — a run continues while cooling', () => {
    for (const tempMode of ['holding', 'cool_storage']) {
      const evs = milestoneEvents([{ id: 'i1', name: 'Inc 1', incubationStart: '2026-06-01', tempMode }], [])
      expect(evs.length).toBe(INCUBATION_MILESTONES.length)
    }
  })

  it('assumes running when the caller does not model modes', () => {
    // Back-compat: callers passing no tempMode must keep their milestones.
    expect(milestoneEvents([{ id: 'i1', name: 'Inc 1', incubationStart: '2026-06-01' }], []).length).toBe(
      INCUBATION_MILESTONES.length,
    )
  })

  it('exports all-day VEVENTs with an exclusive DTEND', () => {
    const evs = milestoneEvents([{ id: 'i1', name: 'Inc 1', incubationStart: '2026-06-01' }], [])
    const ics = milestonesToIcs(evs.slice(0, 1), '2026-08-04T12:00:00.000Z')
    expect(ics).toContain('BEGIN:VCALENDAR')
    expect(ics).toContain('DTSTART;VALUE=DATE:20260601')
    expect(ics).toContain('DTEND;VALUE=DATE:20260602')
    expect(ics).toContain('SUMMARY:Inc 1 — Incubation Start (Day 1)')
    expect(ics).toContain('DTSTAMP:20260804T120000Z')
    expect(ics.endsWith('END:VCALENDAR')).toBe(true)
    expect(ics.split('\r\n').length).toBeGreaterThan(5) // CRLF line endings
  })
})

describe('holding-day reporting', () => {
  // Fixed UTC-day mapper keeps these tests timezone-independent.
  const toYmd = (iso: string) => iso.slice(0, 10)

  const readings = [
    { incubatorId: 'i1', at: '2026-06-01T06:00:00Z', tempC: 30 },
    { incubatorId: 'i1', at: '2026-06-01T18:00:00Z', tempC: 32 }, // mean 31 → incubating
    { incubatorId: 'i1', at: '2026-06-02T06:00:00Z', tempC: 14 },
    { incubatorId: 'i1', at: '2026-06-02T18:00:00Z', tempC: 16 }, // mean 15 → holding
    { incubatorId: 'i2', at: '2026-06-01T06:00:00Z', tempC: 4 }, // cool storage, not holding
    { incubatorId: 'i3', at: '2026-06-01T06:00:00Z', tempC: 20 }, // off / shop ambient
  ]

  it('averages per incubator per day', () => {
    const means = dailyMeanTempByIncubator(readings, toYmd)
    expect(means.get('i1')?.get('2026-06-01')).toBe(31)
    expect(means.get('i1')?.get('2026-06-02')).toBe(15)
  })

  it('counts ONLY days in the holding band', () => {
    const held = holdingDays(dailyMeanTempByIncubator(readings, toYmd))
    expect([...(held.get('i1') ?? [])]).toEqual(['2026-06-02'])
  })

  it('ignores cool storage and an incubator that is simply off', () => {
    const held = holdingDays(dailyMeanTempByIncubator(readings, toYmd))
    // 4 C is below the band; 20 C (shop ambient, switched off) is above it.
    expect(held.get('i2')).toBeUndefined()
    expect(held.get('i3')).toBeUndefined()
  })

  it('uses the day MEAN, so a brief dip into the band is not a holding day', () => {
    const dip = [
      { incubatorId: 'i1', at: '2026-06-03T06:00:00Z', tempC: 30 },
      { incubatorId: 'i1', at: '2026-06-03T07:00:00Z', tempC: 15 }, // door open
      { incubatorId: 'i1', at: '2026-06-03T08:00:00Z', tempC: 30 },
    ]
    expect(holdingDays(dailyMeanTempByIncubator(dip, toYmd)).get('i1')).toBeUndefined()
  })

  it('reports nothing when there are no readings', () => {
    expect(holdingDays(dailyMeanTempByIncubator([], toYmd)).size).toBe(0)
  })

  it('runWindow spans the start through the last milestone', () => {
    expect(runWindow('2026-06-01')).toEqual({ from: '2026-06-01', to: '2026-07-07' })
  })
})

describe('developmental stages', () => {
  it('parses the first day out of each stage label', () => {
    expect(stageStartDay('Day 1 — Worm/Larva')).toBe(1)
    expect(stageStartDay('Day 8–9 — Pupal')).toBe(8)
    expect(stageStartDay('Day 17–18 — Male emergence')).toBe(17)
    expect(stageStartDay('nonsense')).toBeNull()
  })

  it('expects the latest stage whose day has been reached', () => {
    expect(expectedStageForDay(1)).toBe('Day 1 — Worm/Larva')
    expect(expectedStageForDay(4)).toBe('Day 3 — Whitening') // between stages → the earlier one
    expect(expectedStageForDay(9)).toBe('Day 8–9 — Pupal')
    expect(expectedStageForDay(13)).toBe('Day 13 — Male dark eye / Female red eye')
    expect(expectedStageForDay(25)).toBe('Day 20 — Female emergence') // past the end
  })

  it('has no expectation before day 1', () => {
    expect(expectedStageForDay(0)).toBeNull()
    expect(expectedStageForDay(null)).toBeNull()
    expect(expectedStageForDay(undefined)).toBeNull()
  })

  it('measures how far an observation is from the schedule', () => {
    // On day 13 the tray should be at "Male dark eye"; seeing "Pink-Eyed" is one behind.
    expect(stageDelta('Day 13 — Male dark eye / Female red eye', 13)).toBe(0)
    expect(stageDelta('Day 10 — Pink-Eyed', 13)).toBe(-1)
    // Day 14-15 sits between, so Male emergence is TWO stages ahead of day 13.
    expect(stageDelta('Day 17–18 — Male emergence', 13)).toBe(2)
  })

  it('returns no delta for an unknown stage or unknown day', () => {
    expect(stageDelta('Day 13 — Male dark eye / Female red eye', null)).toBeNull()
    expect(stageDelta('made up stage', 13)).toBeNull()
  })
})
